import { createFileRoute } from "@tanstack/react-router";
import { fallback, zodValidator } from "@tanstack/zod-adapter";
import { z } from "zod";
import { DefectRawDataPage } from "@/components/defect-management/raw-data/DefectRawDataPage";

// URL 상태: 탭 / 페이지 / 정렬 / 검색 / 필터 / 비활성 포함
const rawDataSearchSchema = z.object({
  tab: fallback(z.string(), "unclosed").default("unclosed"),
  page: fallback(z.number().int(), 1).default(1),
  pageSize: fallback(z.union([z.number().int(), z.literal("all")]), 100).default(100),
  sort: fallback(z.string(), "").default(""),
  q: fallback(z.string(), "").default(""),
  filters: fallback(z.string(), "").default(""),
  includeInactive: fallback(z.boolean(), false).default(false),
  source: z.string().optional(),
  actualComplete: z.string().optional(),
  closureComplete: z.string().optional(),
  overdue: z.string().optional(),
  atRisk: z.string().optional(),
  atRiskDays: z.string().optional(),
  dueOn: z.string().optional(),
  unplannedActualOn: z.string().optional(),
  asOf: z.string().optional(),
  stage: z.string().optional(),
  remaining_stage: z.string().optional(),
  remaining_asof: z.string().optional(),
  team: z.string().optional(),
  subcontractor: z.string().optional(),
  subsub: z.string().optional(),
  hdecPic: z.string().optional(),
  hdecEng: z.string().optional(),
  capturedBy: z.string().optional(),
  capturedByGroup: z.string().optional(),
  level: z.string().optional(),
  mainTrade: z.string().optional(),
  subTrade: z.string().optional(),
  workType: z.string().optional(),
  classificationSource: z.string().optional(),
  status: z.string().optional(),
  closureStatus: z.string().optional(),
  issueNo: z.string().optional(),
  subcontractorIssueNo: z.string().optional(),
  dateStart: z.string().optional(),
  dateEnd: z.string().optional(),
  dateField: z.string().optional(),
  critical: z.string().optional(),
  priority: z.string().optional(),
  hdecVerification: z.string().optional(),
  hdecReason: z.string().optional(),
  notClosureDone: z.string().optional(),
  catADispute: z.string().optional(),
  plan_group: z.string().optional(),
  building: z.string().optional(),
  roomGroup: z.string().optional(),
});

export const Route = createFileRoute("/_authenticated/closure/snag-management/raw-data")({
  head: () => ({ meta: [{ title: "Snag List — Raw Data" }] }),
  validateSearch: zodValidator(rawDataSearchSchema),
  component: DefectRawDataPage,
});