/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTaskThresholdsRouteImport } from './routes/_authenticated/admin/task-thresholds'
import { Route as AuthenticatedAdminMappingRouteImport } from './routes/_authenticated/admin/mapping'
import { Route as AuthenticatedClosureTaskManagementTreeRouteImport } from './routes/_authenticated/closure/task-management/tree'
import { Route as AuthenticatedClosureTaskManagementRawDataRouteImport } from './routes/_authenticated/closure/task-management/raw-data'
import { Route as AuthenticatedClosureSparePartRawDataRouteImport } from './routes/_authenticated/closure/spare-part/raw-data'
import { Route as AuthenticatedClosureSparePartImportRouteImport } from './routes/_authenticated/closure/spare-part/import'
import { Route as AuthenticatedClosureSparePartDashboardRouteImport } from './routes/_authenticated/closure/spare-part/dashboard'
import { Route as AuthenticatedClosureSparePartAconexSyncRouteImport } from './routes/_authenticated/closure/spare-part/aconex-sync'
import { Route as AuthenticatedClosureTaskManagementImportLogsRouteImport } from './routes/_authenticated/closure/task-management/import.logs'
import { Route as AuthenticatedClosureSparePartRecordsDocRefRouteImport } from './routes/_authenticated/closure/spare-part/records.$docRef'
import { Route as AuthenticatedClosureSparePartImportLogsRouteImport } from './routes/_authenticated/closure/spare-part/import.logs'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTaskThresholdsRoute =
  AuthenticatedAdminTaskThresholdsRouteImport.update({
    id: '/task-thresholds',
    path: '/task-thresholds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMappingRoute =
  AuthenticatedAdminMappingRouteImport.update({
    id: '/mapping',
    path: '/mapping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementTreeRoute =
  AuthenticatedClosureTaskManagementTreeRouteImport.update({
    id: '/closure/task-management/tree',
    path: '/closure/task-management/tree',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementRawDataRoute =
  AuthenticatedClosureTaskManagementRawDataRouteImport.update({
    id: '/closure/task-management/raw-data',
    path: '/closure/task-management/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartRawDataRoute =
  AuthenticatedClosureSparePartRawDataRouteImport.update({
    id: '/closure/spare-part/raw-data',
    path: '/closure/spare-part/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartImportRoute =
  AuthenticatedClosureSparePartImportRouteImport.update({
    id: '/closure/spare-part/import',
    path: '/closure/spare-part/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartDashboardRoute =
  AuthenticatedClosureSparePartDashboardRouteImport.update({
    id: '/closure/spare-part/dashboard',
    path: '/closure/spare-part/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartAconexSyncRoute =
  AuthenticatedClosureSparePartAconexSyncRouteImport.update({
    id: '/closure/spare-part/aconex-sync',
    path: '/closure/spare-part/aconex-sync',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementImportLogsRoute =
  AuthenticatedClosureTaskManagementImportLogsRouteImport.update({
    id: '/closure/task-management/import/logs',
    path: '/closure/task-management/import/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartRecordsDocRefRoute =
  AuthenticatedClosureSparePartRecordsDocRefRouteImport.update({
    id: '/closure/spare-part/records/$docRef',
    path: '/closure/spare-part/records/$docRef',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartImportLogsRoute =
  AuthenticatedClosureSparePartImportLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedClosureSparePartImportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/mapping': typeof AuthenticatedAdminMappingRoute
  '/admin/task-thresholds': typeof AuthenticatedAdminTaskThresholdsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/closure/spare-part/aconex-sync': typeof AuthenticatedClosureSparePartAconexSyncRoute
  '/closure/spare-part/dashboard': typeof AuthenticatedClosureSparePartDashboardRoute
  '/closure/spare-part/import': typeof AuthenticatedClosureSparePartImportRouteWithChildren
  '/closure/spare-part/raw-data': typeof AuthenticatedClosureSparePartRawDataRoute
  '/closure/task-management/raw-data': typeof AuthenticatedClosureTaskManagementRawDataRoute
  '/closure/task-management/tree': typeof AuthenticatedClosureTaskManagementTreeRoute
  '/closure/spare-part/import/logs': typeof AuthenticatedClosureSparePartImportLogsRoute
  '/closure/spare-part/records/$docRef': typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  '/closure/task-management/import/logs': typeof AuthenticatedClosureTaskManagementImportLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/admin/mapping': typeof AuthenticatedAdminMappingRoute
  '/admin/task-thresholds': typeof AuthenticatedAdminTaskThresholdsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/closure/spare-part/aconex-sync': typeof AuthenticatedClosureSparePartAconexSyncRoute
  '/closure/spare-part/dashboard': typeof AuthenticatedClosureSparePartDashboardRoute
  '/closure/spare-part/import': typeof AuthenticatedClosureSparePartImportRouteWithChildren
  '/closure/spare-part/raw-data': typeof AuthenticatedClosureSparePartRawDataRoute
  '/closure/task-management/raw-data': typeof AuthenticatedClosureTaskManagementRawDataRoute
  '/closure/task-management/tree': typeof AuthenticatedClosureTaskManagementTreeRoute
  '/closure/spare-part/import/logs': typeof AuthenticatedClosureSparePartImportLogsRoute
  '/closure/spare-part/records/$docRef': typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  '/closure/task-management/import/logs': typeof AuthenticatedClosureTaskManagementImportLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/mapping': typeof AuthenticatedAdminMappingRoute
  '/_authenticated/admin/task-thresholds': typeof AuthenticatedAdminTaskThresholdsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/closure/spare-part/aconex-sync': typeof AuthenticatedClosureSparePartAconexSyncRoute
  '/_authenticated/closure/spare-part/dashboard': typeof AuthenticatedClosureSparePartDashboardRoute
  '/_authenticated/closure/spare-part/import': typeof AuthenticatedClosureSparePartImportRouteWithChildren
  '/_authenticated/closure/spare-part/raw-data': typeof AuthenticatedClosureSparePartRawDataRoute
  '/_authenticated/closure/task-management/raw-data': typeof AuthenticatedClosureTaskManagementRawDataRoute
  '/_authenticated/closure/task-management/tree': typeof AuthenticatedClosureTaskManagementTreeRoute
  '/_authenticated/closure/spare-part/import/logs': typeof AuthenticatedClosureSparePartImportLogsRoute
  '/_authenticated/closure/spare-part/records/$docRef': typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  '/_authenticated/closure/task-management/import/logs': typeof AuthenticatedClosureTaskManagementImportLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/admin'
    | '/admin/mapping'
    | '/admin/task-thresholds'
    | '/admin/'
    | '/closure/spare-part/aconex-sync'
    | '/closure/spare-part/dashboard'
    | '/closure/spare-part/import'
    | '/closure/spare-part/raw-data'
    | '/closure/task-management/raw-data'
    | '/closure/task-management/tree'
    | '/closure/spare-part/import/logs'
    | '/closure/spare-part/records/$docRef'
    | '/closure/task-management/import/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/admin/mapping'
    | '/admin/task-thresholds'
    | '/admin'
    | '/closure/spare-part/aconex-sync'
    | '/closure/spare-part/dashboard'
    | '/closure/spare-part/import'
    | '/closure/spare-part/raw-data'
    | '/closure/task-management/raw-data'
    | '/closure/task-management/tree'
    | '/closure/spare-part/import/logs'
    | '/closure/spare-part/records/$docRef'
    | '/closure/task-management/import/logs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/_authenticated/admin'
    | '/_authenticated/admin/mapping'
    | '/_authenticated/admin/task-thresholds'
    | '/_authenticated/admin/'
    | '/_authenticated/closure/spare-part/aconex-sync'
    | '/_authenticated/closure/spare-part/dashboard'
    | '/_authenticated/closure/spare-part/import'
    | '/_authenticated/closure/spare-part/raw-data'
    | '/_authenticated/closure/task-management/raw-data'
    | '/_authenticated/closure/task-management/tree'
    | '/_authenticated/closure/spare-part/import/logs'
    | '/_authenticated/closure/spare-part/records/$docRef'
    | '/_authenticated/closure/task-management/import/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/task-thresholds': {
      id: '/_authenticated/admin/task-thresholds'
      path: '/task-thresholds'
      fullPath: '/admin/task-thresholds'
      preLoaderRoute: typeof AuthenticatedAdminTaskThresholdsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mapping': {
      id: '/_authenticated/admin/mapping'
      path: '/mapping'
      fullPath: '/admin/mapping'
      preLoaderRoute: typeof AuthenticatedAdminMappingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/closure/task-management/tree': {
      id: '/_authenticated/closure/task-management/tree'
      path: '/closure/task-management/tree'
      fullPath: '/closure/task-management/tree'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementTreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/raw-data': {
      id: '/_authenticated/closure/task-management/raw-data'
      path: '/closure/task-management/raw-data'
      fullPath: '/closure/task-management/raw-data'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/raw-data': {
      id: '/_authenticated/closure/spare-part/raw-data'
      path: '/closure/spare-part/raw-data'
      fullPath: '/closure/spare-part/raw-data'
      preLoaderRoute: typeof AuthenticatedClosureSparePartRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/import': {
      id: '/_authenticated/closure/spare-part/import'
      path: '/closure/spare-part/import'
      fullPath: '/closure/spare-part/import'
      preLoaderRoute: typeof AuthenticatedClosureSparePartImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/dashboard': {
      id: '/_authenticated/closure/spare-part/dashboard'
      path: '/closure/spare-part/dashboard'
      fullPath: '/closure/spare-part/dashboard'
      preLoaderRoute: typeof AuthenticatedClosureSparePartDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/aconex-sync': {
      id: '/_authenticated/closure/spare-part/aconex-sync'
      path: '/closure/spare-part/aconex-sync'
      fullPath: '/closure/spare-part/aconex-sync'
      preLoaderRoute: typeof AuthenticatedClosureSparePartAconexSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/import/logs': {
      id: '/_authenticated/closure/task-management/import/logs'
      path: '/closure/task-management/import/logs'
      fullPath: '/closure/task-management/import/logs'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementImportLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/records/$docRef': {
      id: '/_authenticated/closure/spare-part/records/$docRef'
      path: '/closure/spare-part/records/$docRef'
      fullPath: '/closure/spare-part/records/$docRef'
      preLoaderRoute: typeof AuthenticatedClosureSparePartRecordsDocRefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/import/logs': {
      id: '/_authenticated/closure/spare-part/import/logs'
      path: '/logs'
      fullPath: '/closure/spare-part/import/logs'
      preLoaderRoute: typeof AuthenticatedClosureSparePartImportLogsRouteImport
      parentRoute: typeof AuthenticatedClosureSparePartImportRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminMappingRoute: typeof AuthenticatedAdminMappingRoute
  AuthenticatedAdminTaskThresholdsRoute: typeof AuthenticatedAdminTaskThresholdsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminMappingRoute: AuthenticatedAdminMappingRoute,
    AuthenticatedAdminTaskThresholdsRoute:
      AuthenticatedAdminTaskThresholdsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClosureSparePartImportRouteChildren {
  AuthenticatedClosureSparePartImportLogsRoute: typeof AuthenticatedClosureSparePartImportLogsRoute
}

const AuthenticatedClosureSparePartImportRouteChildren: AuthenticatedClosureSparePartImportRouteChildren =
  {
    AuthenticatedClosureSparePartImportLogsRoute:
      AuthenticatedClosureSparePartImportLogsRoute,
  }

const AuthenticatedClosureSparePartImportRouteWithChildren =
  AuthenticatedClosureSparePartImportRoute._addFileChildren(
    AuthenticatedClosureSparePartImportRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClosureSparePartAconexSyncRoute: typeof AuthenticatedClosureSparePartAconexSyncRoute
  AuthenticatedClosureSparePartDashboardRoute: typeof AuthenticatedClosureSparePartDashboardRoute
  AuthenticatedClosureSparePartImportRoute: typeof AuthenticatedClosureSparePartImportRouteWithChildren
  AuthenticatedClosureSparePartRawDataRoute: typeof AuthenticatedClosureSparePartRawDataRoute
  AuthenticatedClosureTaskManagementRawDataRoute: typeof AuthenticatedClosureTaskManagementRawDataRoute
  AuthenticatedClosureTaskManagementTreeRoute: typeof AuthenticatedClosureTaskManagementTreeRoute
  AuthenticatedClosureSparePartRecordsDocRefRoute: typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  AuthenticatedClosureTaskManagementImportLogsRoute: typeof AuthenticatedClosureTaskManagementImportLogsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClosureSparePartAconexSyncRoute:
    AuthenticatedClosureSparePartAconexSyncRoute,
  AuthenticatedClosureSparePartDashboardRoute:
    AuthenticatedClosureSparePartDashboardRoute,
  AuthenticatedClosureSparePartImportRoute:
    AuthenticatedClosureSparePartImportRouteWithChildren,
  AuthenticatedClosureSparePartRawDataRoute:
    AuthenticatedClosureSparePartRawDataRoute,
  AuthenticatedClosureTaskManagementRawDataRoute:
    AuthenticatedClosureTaskManagementRawDataRoute,
  AuthenticatedClosureTaskManagementTreeRoute:
    AuthenticatedClosureTaskManagementTreeRoute,
  AuthenticatedClosureSparePartRecordsDocRefRoute:
    AuthenticatedClosureSparePartRecordsDocRefRoute,
  AuthenticatedClosureTaskManagementImportLogsRoute:
    AuthenticatedClosureTaskManagementImportLogsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
