/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as AuthenticatedResourceDashboardRouteImport } from './routes/_authenticated/resource/dashboard'
import { Route as AuthenticatedOutstandingDashboardRouteImport } from './routes/_authenticated/outstanding/dashboard'
import { Route as AuthenticatedImportLogLogsRouteImport } from './routes/_authenticated/import-log/logs'
import { Route as AuthenticatedImportLogImportRouteImport } from './routes/_authenticated/import-log/import'
import { Route as AuthenticatedCloseoutDashboardRouteImport } from './routes/_authenticated/closeout/dashboard'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTaskThresholdsRouteImport } from './routes/_authenticated/admin/task-thresholds'
import { Route as AuthenticatedAdminMastersRouteImport } from './routes/_authenticated/admin/masters'
import { Route as AuthenticatedAdminMappingRouteImport } from './routes/_authenticated/admin/mapping'
import { Route as AuthenticatedAdminBackupRouteImport } from './routes/_authenticated/admin/backup'
import { Route as AuthenticatedClosureDashboardIndexRouteImport } from './routes/_authenticated/closure/dashboard/index'
import { Route as ApiPublicBackupAutoSnapshotRouteImport } from './routes/api/public/backup/auto-snapshot'
import { Route as ApiPublicBackupArchiveDownloadRouteImport } from './routes/api/public/backup/archive-download'
import { Route as AuthenticatedResourceDmrRawDataRouteImport } from './routes/_authenticated/resource/dmr/raw-data'
import { Route as AuthenticatedResourceDmrImportRouteImport } from './routes/_authenticated/resource/dmr/import'
import { Route as AuthenticatedResourceDmrDashboardRouteImport } from './routes/_authenticated/resource/dmr/dashboard'
import { Route as AuthenticatedClosureTaskManagementTreeRouteImport } from './routes/_authenticated/closure/task-management/tree'
import { Route as AuthenticatedClosureTaskManagementScheduleRevisionRouteImport } from './routes/_authenticated/closure/task-management/schedule-revision'
import { Route as AuthenticatedClosureTaskManagementRawDataRouteImport } from './routes/_authenticated/closure/task-management/raw-data'
import { Route as AuthenticatedClosureTaskManagementDashboardRouteImport } from './routes/_authenticated/closure/task-management/dashboard'
import { Route as AuthenticatedClosureSparePartRawDataRouteImport } from './routes/_authenticated/closure/spare-part/raw-data'
import { Route as AuthenticatedClosureSparePartImportRouteImport } from './routes/_authenticated/closure/spare-part/import'
import { Route as AuthenticatedClosureSparePartAconexSyncRouteImport } from './routes/_authenticated/closure/spare-part/aconex-sync'
import { Route as AuthenticatedClosureSnagManagementSettingsRouteImport } from './routes/_authenticated/closure/snag-management/settings'
import { Route as AuthenticatedClosureSnagManagementRawDataRouteImport } from './routes/_authenticated/closure/snag-management/raw-data'
import { Route as AuthenticatedClosureSnagManagementProgressRouteImport } from './routes/_authenticated/closure/snag-management/progress'
import { Route as AuthenticatedClosureSnagManagementDashboardRouteImport } from './routes/_authenticated/closure/snag-management/dashboard'
import { Route as AuthenticatedClosureDashboardWarrantyRouteImport } from './routes/_authenticated/closure/dashboard/warranty'
import { Route as AuthenticatedClosureDashboardTaskRouteImport } from './routes/_authenticated/closure/dashboard/task'
import { Route as AuthenticatedClosureDashboardSparePartRouteImport } from './routes/_authenticated/closure/dashboard/spare-part'
import { Route as AuthenticatedClosureDashboardAsBuiltRouteImport } from './routes/_authenticated/closure/dashboard/as-built'
import { Route as AuthenticatedClosureAbdRawDataRouteImport } from './routes/_authenticated/closure/abd/raw-data'
import { Route as AuthenticatedClosureAbdProgressRouteImport } from './routes/_authenticated/closure/abd/progress'
import { Route as AuthenticatedClosureAbdImportRouteImport } from './routes/_authenticated/closure/abd/import'
import { Route as AuthenticatedClosureAbdDashboardRouteImport } from './routes/_authenticated/closure/abd/dashboard'
import { Route as AuthenticatedClosureSnagManagementImportIndexRouteImport } from './routes/_authenticated/closure/snag-management/import.index'
import { Route as AuthenticatedClosureTaskManagementImportLogsRouteImport } from './routes/_authenticated/closure/task-management/import.logs'
import { Route as AuthenticatedClosureTaskManagementDetailIdRouteImport } from './routes/_authenticated/closure/task-management/detail.$id'
import { Route as AuthenticatedClosureSparePartRecordsDocRefRouteImport } from './routes/_authenticated/closure/spare-part/records.$docRef'
import { Route as AuthenticatedClosureSparePartImportLogsRouteImport } from './routes/_authenticated/closure/spare-part/import.logs'
import { Route as AuthenticatedClosureSnagManagementImportLogsRouteImport } from './routes/_authenticated/closure/snag-management/import.logs'
import { Route as AuthenticatedClosureSnagManagementDetailIdRouteImport } from './routes/_authenticated/closure/snag-management/detail.$id'
import { Route as AuthenticatedClosureAbdImportLogsRouteImport } from './routes/_authenticated/closure/abd/import.logs'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourceDashboardRoute =
  AuthenticatedResourceDashboardRouteImport.update({
    id: '/resource/dashboard',
    path: '/resource/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOutstandingDashboardRoute =
  AuthenticatedOutstandingDashboardRouteImport.update({
    id: '/outstanding/dashboard',
    path: '/outstanding/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportLogLogsRoute =
  AuthenticatedImportLogLogsRouteImport.update({
    id: '/import-log/logs',
    path: '/import-log/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportLogImportRoute =
  AuthenticatedImportLogImportRouteImport.update({
    id: '/import-log/import',
    path: '/import-log/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCloseoutDashboardRoute =
  AuthenticatedCloseoutDashboardRouteImport.update({
    id: '/closeout/dashboard',
    path: '/closeout/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTaskThresholdsRoute =
  AuthenticatedAdminTaskThresholdsRouteImport.update({
    id: '/task-thresholds',
    path: '/task-thresholds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMastersRoute =
  AuthenticatedAdminMastersRouteImport.update({
    id: '/masters',
    path: '/masters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMappingRoute =
  AuthenticatedAdminMappingRouteImport.update({
    id: '/mapping',
    path: '/mapping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBackupRoute =
  AuthenticatedAdminBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClosureDashboardIndexRoute =
  AuthenticatedClosureDashboardIndexRouteImport.update({
    id: '/closure/dashboard/',
    path: '/closure/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBackupAutoSnapshotRoute =
  ApiPublicBackupAutoSnapshotRouteImport.update({
    id: '/api/public/backup/auto-snapshot',
    path: '/api/public/backup/auto-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackupArchiveDownloadRoute =
  ApiPublicBackupArchiveDownloadRouteImport.update({
    id: '/api/public/backup/archive-download',
    path: '/api/public/backup/archive-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedResourceDmrRawDataRoute =
  AuthenticatedResourceDmrRawDataRouteImport.update({
    id: '/resource/dmr/raw-data',
    path: '/resource/dmr/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourceDmrImportRoute =
  AuthenticatedResourceDmrImportRouteImport.update({
    id: '/resource/dmr/import',
    path: '/resource/dmr/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourceDmrDashboardRoute =
  AuthenticatedResourceDmrDashboardRouteImport.update({
    id: '/resource/dmr/dashboard',
    path: '/resource/dmr/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementTreeRoute =
  AuthenticatedClosureTaskManagementTreeRouteImport.update({
    id: '/closure/task-management/tree',
    path: '/closure/task-management/tree',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementScheduleRevisionRoute =
  AuthenticatedClosureTaskManagementScheduleRevisionRouteImport.update({
    id: '/closure/task-management/schedule-revision',
    path: '/closure/task-management/schedule-revision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementRawDataRoute =
  AuthenticatedClosureTaskManagementRawDataRouteImport.update({
    id: '/closure/task-management/raw-data',
    path: '/closure/task-management/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementDashboardRoute =
  AuthenticatedClosureTaskManagementDashboardRouteImport.update({
    id: '/closure/task-management/dashboard',
    path: '/closure/task-management/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartRawDataRoute =
  AuthenticatedClosureSparePartRawDataRouteImport.update({
    id: '/closure/spare-part/raw-data',
    path: '/closure/spare-part/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartImportRoute =
  AuthenticatedClosureSparePartImportRouteImport.update({
    id: '/closure/spare-part/import',
    path: '/closure/spare-part/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartAconexSyncRoute =
  AuthenticatedClosureSparePartAconexSyncRouteImport.update({
    id: '/closure/spare-part/aconex-sync',
    path: '/closure/spare-part/aconex-sync',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSnagManagementSettingsRoute =
  AuthenticatedClosureSnagManagementSettingsRouteImport.update({
    id: '/closure/snag-management/settings',
    path: '/closure/snag-management/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSnagManagementRawDataRoute =
  AuthenticatedClosureSnagManagementRawDataRouteImport.update({
    id: '/closure/snag-management/raw-data',
    path: '/closure/snag-management/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSnagManagementProgressRoute =
  AuthenticatedClosureSnagManagementProgressRouteImport.update({
    id: '/closure/snag-management/progress',
    path: '/closure/snag-management/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSnagManagementDashboardRoute =
  AuthenticatedClosureSnagManagementDashboardRouteImport.update({
    id: '/closure/snag-management/dashboard',
    path: '/closure/snag-management/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureDashboardWarrantyRoute =
  AuthenticatedClosureDashboardWarrantyRouteImport.update({
    id: '/closure/dashboard/warranty',
    path: '/closure/dashboard/warranty',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureDashboardTaskRoute =
  AuthenticatedClosureDashboardTaskRouteImport.update({
    id: '/closure/dashboard/task',
    path: '/closure/dashboard/task',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureDashboardSparePartRoute =
  AuthenticatedClosureDashboardSparePartRouteImport.update({
    id: '/closure/dashboard/spare-part',
    path: '/closure/dashboard/spare-part',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureDashboardAsBuiltRoute =
  AuthenticatedClosureDashboardAsBuiltRouteImport.update({
    id: '/closure/dashboard/as-built',
    path: '/closure/dashboard/as-built',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureAbdRawDataRoute =
  AuthenticatedClosureAbdRawDataRouteImport.update({
    id: '/closure/abd/raw-data',
    path: '/closure/abd/raw-data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureAbdProgressRoute =
  AuthenticatedClosureAbdProgressRouteImport.update({
    id: '/closure/abd/progress',
    path: '/closure/abd/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureAbdImportRoute =
  AuthenticatedClosureAbdImportRouteImport.update({
    id: '/closure/abd/import',
    path: '/closure/abd/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureAbdDashboardRoute =
  AuthenticatedClosureAbdDashboardRouteImport.update({
    id: '/closure/abd/dashboard',
    path: '/closure/abd/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSnagManagementImportIndexRoute =
  AuthenticatedClosureSnagManagementImportIndexRouteImport.update({
    id: '/closure/snag-management/import/',
    path: '/closure/snag-management/import/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementImportLogsRoute =
  AuthenticatedClosureTaskManagementImportLogsRouteImport.update({
    id: '/closure/task-management/import/logs',
    path: '/closure/task-management/import/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureTaskManagementDetailIdRoute =
  AuthenticatedClosureTaskManagementDetailIdRouteImport.update({
    id: '/closure/task-management/detail/$id',
    path: '/closure/task-management/detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartRecordsDocRefRoute =
  AuthenticatedClosureSparePartRecordsDocRefRouteImport.update({
    id: '/closure/spare-part/records/$docRef',
    path: '/closure/spare-part/records/$docRef',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSparePartImportLogsRoute =
  AuthenticatedClosureSparePartImportLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedClosureSparePartImportRoute,
  } as any)
const AuthenticatedClosureSnagManagementImportLogsRoute =
  AuthenticatedClosureSnagManagementImportLogsRouteImport.update({
    id: '/closure/snag-management/import/logs',
    path: '/closure/snag-management/import/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureSnagManagementDetailIdRoute =
  AuthenticatedClosureSnagManagementDetailIdRouteImport.update({
    id: '/closure/snag-management/detail/$id',
    path: '/closure/snag-management/detail/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClosureAbdImportLogsRoute =
  AuthenticatedClosureAbdImportLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedClosureAbdImportRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/mapping': typeof AuthenticatedAdminMappingRoute
  '/admin/masters': typeof AuthenticatedAdminMastersRoute
  '/admin/task-thresholds': typeof AuthenticatedAdminTaskThresholdsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/closeout/dashboard': typeof AuthenticatedCloseoutDashboardRoute
  '/import-log/import': typeof AuthenticatedImportLogImportRoute
  '/import-log/logs': typeof AuthenticatedImportLogLogsRoute
  '/outstanding/dashboard': typeof AuthenticatedOutstandingDashboardRoute
  '/resource/dashboard': typeof AuthenticatedResourceDashboardRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/closure/abd/dashboard': typeof AuthenticatedClosureAbdDashboardRoute
  '/closure/abd/import': typeof AuthenticatedClosureAbdImportRouteWithChildren
  '/closure/abd/progress': typeof AuthenticatedClosureAbdProgressRoute
  '/closure/abd/raw-data': typeof AuthenticatedClosureAbdRawDataRoute
  '/closure/dashboard/as-built': typeof AuthenticatedClosureDashboardAsBuiltRoute
  '/closure/dashboard/spare-part': typeof AuthenticatedClosureDashboardSparePartRoute
  '/closure/dashboard/task': typeof AuthenticatedClosureDashboardTaskRoute
  '/closure/dashboard/warranty': typeof AuthenticatedClosureDashboardWarrantyRoute
  '/closure/snag-management/dashboard': typeof AuthenticatedClosureSnagManagementDashboardRoute
  '/closure/snag-management/progress': typeof AuthenticatedClosureSnagManagementProgressRoute
  '/closure/snag-management/raw-data': typeof AuthenticatedClosureSnagManagementRawDataRoute
  '/closure/snag-management/settings': typeof AuthenticatedClosureSnagManagementSettingsRoute
  '/closure/spare-part/aconex-sync': typeof AuthenticatedClosureSparePartAconexSyncRoute
  '/closure/spare-part/import': typeof AuthenticatedClosureSparePartImportRouteWithChildren
  '/closure/spare-part/raw-data': typeof AuthenticatedClosureSparePartRawDataRoute
  '/closure/task-management/dashboard': typeof AuthenticatedClosureTaskManagementDashboardRoute
  '/closure/task-management/raw-data': typeof AuthenticatedClosureTaskManagementRawDataRoute
  '/closure/task-management/schedule-revision': typeof AuthenticatedClosureTaskManagementScheduleRevisionRoute
  '/closure/task-management/tree': typeof AuthenticatedClosureTaskManagementTreeRoute
  '/resource/dmr/dashboard': typeof AuthenticatedResourceDmrDashboardRoute
  '/resource/dmr/import': typeof AuthenticatedResourceDmrImportRoute
  '/resource/dmr/raw-data': typeof AuthenticatedResourceDmrRawDataRoute
  '/api/public/backup/archive-download': typeof ApiPublicBackupArchiveDownloadRoute
  '/api/public/backup/auto-snapshot': typeof ApiPublicBackupAutoSnapshotRoute
  '/closure/dashboard/': typeof AuthenticatedClosureDashboardIndexRoute
  '/closure/abd/import/logs': typeof AuthenticatedClosureAbdImportLogsRoute
  '/closure/snag-management/detail/$id': typeof AuthenticatedClosureSnagManagementDetailIdRoute
  '/closure/snag-management/import/logs': typeof AuthenticatedClosureSnagManagementImportLogsRoute
  '/closure/spare-part/import/logs': typeof AuthenticatedClosureSparePartImportLogsRoute
  '/closure/spare-part/records/$docRef': typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  '/closure/task-management/detail/$id': typeof AuthenticatedClosureTaskManagementDetailIdRoute
  '/closure/task-management/import/logs': typeof AuthenticatedClosureTaskManagementImportLogsRoute
  '/closure/snag-management/import/': typeof AuthenticatedClosureSnagManagementImportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/admin/mapping': typeof AuthenticatedAdminMappingRoute
  '/admin/masters': typeof AuthenticatedAdminMastersRoute
  '/admin/task-thresholds': typeof AuthenticatedAdminTaskThresholdsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/closeout/dashboard': typeof AuthenticatedCloseoutDashboardRoute
  '/import-log/import': typeof AuthenticatedImportLogImportRoute
  '/import-log/logs': typeof AuthenticatedImportLogLogsRoute
  '/outstanding/dashboard': typeof AuthenticatedOutstandingDashboardRoute
  '/resource/dashboard': typeof AuthenticatedResourceDashboardRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/closure/abd/dashboard': typeof AuthenticatedClosureAbdDashboardRoute
  '/closure/abd/import': typeof AuthenticatedClosureAbdImportRouteWithChildren
  '/closure/abd/progress': typeof AuthenticatedClosureAbdProgressRoute
  '/closure/abd/raw-data': typeof AuthenticatedClosureAbdRawDataRoute
  '/closure/dashboard/as-built': typeof AuthenticatedClosureDashboardAsBuiltRoute
  '/closure/dashboard/spare-part': typeof AuthenticatedClosureDashboardSparePartRoute
  '/closure/dashboard/task': typeof AuthenticatedClosureDashboardTaskRoute
  '/closure/dashboard/warranty': typeof AuthenticatedClosureDashboardWarrantyRoute
  '/closure/snag-management/dashboard': typeof AuthenticatedClosureSnagManagementDashboardRoute
  '/closure/snag-management/progress': typeof AuthenticatedClosureSnagManagementProgressRoute
  '/closure/snag-management/raw-data': typeof AuthenticatedClosureSnagManagementRawDataRoute
  '/closure/snag-management/settings': typeof AuthenticatedClosureSnagManagementSettingsRoute
  '/closure/spare-part/aconex-sync': typeof AuthenticatedClosureSparePartAconexSyncRoute
  '/closure/spare-part/import': typeof AuthenticatedClosureSparePartImportRouteWithChildren
  '/closure/spare-part/raw-data': typeof AuthenticatedClosureSparePartRawDataRoute
  '/closure/task-management/dashboard': typeof AuthenticatedClosureTaskManagementDashboardRoute
  '/closure/task-management/raw-data': typeof AuthenticatedClosureTaskManagementRawDataRoute
  '/closure/task-management/schedule-revision': typeof AuthenticatedClosureTaskManagementScheduleRevisionRoute
  '/closure/task-management/tree': typeof AuthenticatedClosureTaskManagementTreeRoute
  '/resource/dmr/dashboard': typeof AuthenticatedResourceDmrDashboardRoute
  '/resource/dmr/import': typeof AuthenticatedResourceDmrImportRoute
  '/resource/dmr/raw-data': typeof AuthenticatedResourceDmrRawDataRoute
  '/api/public/backup/archive-download': typeof ApiPublicBackupArchiveDownloadRoute
  '/api/public/backup/auto-snapshot': typeof ApiPublicBackupAutoSnapshotRoute
  '/closure/dashboard': typeof AuthenticatedClosureDashboardIndexRoute
  '/closure/abd/import/logs': typeof AuthenticatedClosureAbdImportLogsRoute
  '/closure/snag-management/detail/$id': typeof AuthenticatedClosureSnagManagementDetailIdRoute
  '/closure/snag-management/import/logs': typeof AuthenticatedClosureSnagManagementImportLogsRoute
  '/closure/spare-part/import/logs': typeof AuthenticatedClosureSparePartImportLogsRoute
  '/closure/spare-part/records/$docRef': typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  '/closure/task-management/detail/$id': typeof AuthenticatedClosureTaskManagementDetailIdRoute
  '/closure/task-management/import/logs': typeof AuthenticatedClosureTaskManagementImportLogsRoute
  '/closure/snag-management/import': typeof AuthenticatedClosureSnagManagementImportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/backup': typeof AuthenticatedAdminBackupRoute
  '/_authenticated/admin/mapping': typeof AuthenticatedAdminMappingRoute
  '/_authenticated/admin/masters': typeof AuthenticatedAdminMastersRoute
  '/_authenticated/admin/task-thresholds': typeof AuthenticatedAdminTaskThresholdsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/closeout/dashboard': typeof AuthenticatedCloseoutDashboardRoute
  '/_authenticated/import-log/import': typeof AuthenticatedImportLogImportRoute
  '/_authenticated/import-log/logs': typeof AuthenticatedImportLogLogsRoute
  '/_authenticated/outstanding/dashboard': typeof AuthenticatedOutstandingDashboardRoute
  '/_authenticated/resource/dashboard': typeof AuthenticatedResourceDashboardRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/closure/abd/dashboard': typeof AuthenticatedClosureAbdDashboardRoute
  '/_authenticated/closure/abd/import': typeof AuthenticatedClosureAbdImportRouteWithChildren
  '/_authenticated/closure/abd/progress': typeof AuthenticatedClosureAbdProgressRoute
  '/_authenticated/closure/abd/raw-data': typeof AuthenticatedClosureAbdRawDataRoute
  '/_authenticated/closure/dashboard/as-built': typeof AuthenticatedClosureDashboardAsBuiltRoute
  '/_authenticated/closure/dashboard/spare-part': typeof AuthenticatedClosureDashboardSparePartRoute
  '/_authenticated/closure/dashboard/task': typeof AuthenticatedClosureDashboardTaskRoute
  '/_authenticated/closure/dashboard/warranty': typeof AuthenticatedClosureDashboardWarrantyRoute
  '/_authenticated/closure/snag-management/dashboard': typeof AuthenticatedClosureSnagManagementDashboardRoute
  '/_authenticated/closure/snag-management/progress': typeof AuthenticatedClosureSnagManagementProgressRoute
  '/_authenticated/closure/snag-management/raw-data': typeof AuthenticatedClosureSnagManagementRawDataRoute
  '/_authenticated/closure/snag-management/settings': typeof AuthenticatedClosureSnagManagementSettingsRoute
  '/_authenticated/closure/spare-part/aconex-sync': typeof AuthenticatedClosureSparePartAconexSyncRoute
  '/_authenticated/closure/spare-part/import': typeof AuthenticatedClosureSparePartImportRouteWithChildren
  '/_authenticated/closure/spare-part/raw-data': typeof AuthenticatedClosureSparePartRawDataRoute
  '/_authenticated/closure/task-management/dashboard': typeof AuthenticatedClosureTaskManagementDashboardRoute
  '/_authenticated/closure/task-management/raw-data': typeof AuthenticatedClosureTaskManagementRawDataRoute
  '/_authenticated/closure/task-management/schedule-revision': typeof AuthenticatedClosureTaskManagementScheduleRevisionRoute
  '/_authenticated/closure/task-management/tree': typeof AuthenticatedClosureTaskManagementTreeRoute
  '/_authenticated/resource/dmr/dashboard': typeof AuthenticatedResourceDmrDashboardRoute
  '/_authenticated/resource/dmr/import': typeof AuthenticatedResourceDmrImportRoute
  '/_authenticated/resource/dmr/raw-data': typeof AuthenticatedResourceDmrRawDataRoute
  '/api/public/backup/archive-download': typeof ApiPublicBackupArchiveDownloadRoute
  '/api/public/backup/auto-snapshot': typeof ApiPublicBackupAutoSnapshotRoute
  '/_authenticated/closure/dashboard/': typeof AuthenticatedClosureDashboardIndexRoute
  '/_authenticated/closure/abd/import/logs': typeof AuthenticatedClosureAbdImportLogsRoute
  '/_authenticated/closure/snag-management/detail/$id': typeof AuthenticatedClosureSnagManagementDetailIdRoute
  '/_authenticated/closure/snag-management/import/logs': typeof AuthenticatedClosureSnagManagementImportLogsRoute
  '/_authenticated/closure/spare-part/import/logs': typeof AuthenticatedClosureSparePartImportLogsRoute
  '/_authenticated/closure/spare-part/records/$docRef': typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  '/_authenticated/closure/task-management/detail/$id': typeof AuthenticatedClosureTaskManagementDetailIdRoute
  '/_authenticated/closure/task-management/import/logs': typeof AuthenticatedClosureTaskManagementImportLogsRoute
  '/_authenticated/closure/snag-management/import/': typeof AuthenticatedClosureSnagManagementImportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/admin'
    | '/admin/backup'
    | '/admin/mapping'
    | '/admin/masters'
    | '/admin/task-thresholds'
    | '/admin/users'
    | '/closeout/dashboard'
    | '/import-log/import'
    | '/import-log/logs'
    | '/outstanding/dashboard'
    | '/resource/dashboard'
    | '/api/public/version'
    | '/admin/'
    | '/closure/abd/dashboard'
    | '/closure/abd/import'
    | '/closure/abd/progress'
    | '/closure/abd/raw-data'
    | '/closure/dashboard/as-built'
    | '/closure/dashboard/spare-part'
    | '/closure/dashboard/task'
    | '/closure/dashboard/warranty'
    | '/closure/snag-management/dashboard'
    | '/closure/snag-management/progress'
    | '/closure/snag-management/raw-data'
    | '/closure/snag-management/settings'
    | '/closure/spare-part/aconex-sync'
    | '/closure/spare-part/import'
    | '/closure/spare-part/raw-data'
    | '/closure/task-management/dashboard'
    | '/closure/task-management/raw-data'
    | '/closure/task-management/schedule-revision'
    | '/closure/task-management/tree'
    | '/resource/dmr/dashboard'
    | '/resource/dmr/import'
    | '/resource/dmr/raw-data'
    | '/api/public/backup/archive-download'
    | '/api/public/backup/auto-snapshot'
    | '/closure/dashboard/'
    | '/closure/abd/import/logs'
    | '/closure/snag-management/detail/$id'
    | '/closure/snag-management/import/logs'
    | '/closure/spare-part/import/logs'
    | '/closure/spare-part/records/$docRef'
    | '/closure/task-management/detail/$id'
    | '/closure/task-management/import/logs'
    | '/closure/snag-management/import/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/admin/backup'
    | '/admin/mapping'
    | '/admin/masters'
    | '/admin/task-thresholds'
    | '/admin/users'
    | '/closeout/dashboard'
    | '/import-log/import'
    | '/import-log/logs'
    | '/outstanding/dashboard'
    | '/resource/dashboard'
    | '/api/public/version'
    | '/admin'
    | '/closure/abd/dashboard'
    | '/closure/abd/import'
    | '/closure/abd/progress'
    | '/closure/abd/raw-data'
    | '/closure/dashboard/as-built'
    | '/closure/dashboard/spare-part'
    | '/closure/dashboard/task'
    | '/closure/dashboard/warranty'
    | '/closure/snag-management/dashboard'
    | '/closure/snag-management/progress'
    | '/closure/snag-management/raw-data'
    | '/closure/snag-management/settings'
    | '/closure/spare-part/aconex-sync'
    | '/closure/spare-part/import'
    | '/closure/spare-part/raw-data'
    | '/closure/task-management/dashboard'
    | '/closure/task-management/raw-data'
    | '/closure/task-management/schedule-revision'
    | '/closure/task-management/tree'
    | '/resource/dmr/dashboard'
    | '/resource/dmr/import'
    | '/resource/dmr/raw-data'
    | '/api/public/backup/archive-download'
    | '/api/public/backup/auto-snapshot'
    | '/closure/dashboard'
    | '/closure/abd/import/logs'
    | '/closure/snag-management/detail/$id'
    | '/closure/snag-management/import/logs'
    | '/closure/spare-part/import/logs'
    | '/closure/spare-part/records/$docRef'
    | '/closure/task-management/detail/$id'
    | '/closure/task-management/import/logs'
    | '/closure/snag-management/import'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/_authenticated/admin'
    | '/_authenticated/admin/backup'
    | '/_authenticated/admin/mapping'
    | '/_authenticated/admin/masters'
    | '/_authenticated/admin/task-thresholds'
    | '/_authenticated/admin/users'
    | '/_authenticated/closeout/dashboard'
    | '/_authenticated/import-log/import'
    | '/_authenticated/import-log/logs'
    | '/_authenticated/outstanding/dashboard'
    | '/_authenticated/resource/dashboard'
    | '/api/public/version'
    | '/_authenticated/admin/'
    | '/_authenticated/closure/abd/dashboard'
    | '/_authenticated/closure/abd/import'
    | '/_authenticated/closure/abd/progress'
    | '/_authenticated/closure/abd/raw-data'
    | '/_authenticated/closure/dashboard/as-built'
    | '/_authenticated/closure/dashboard/spare-part'
    | '/_authenticated/closure/dashboard/task'
    | '/_authenticated/closure/dashboard/warranty'
    | '/_authenticated/closure/snag-management/dashboard'
    | '/_authenticated/closure/snag-management/progress'
    | '/_authenticated/closure/snag-management/raw-data'
    | '/_authenticated/closure/snag-management/settings'
    | '/_authenticated/closure/spare-part/aconex-sync'
    | '/_authenticated/closure/spare-part/import'
    | '/_authenticated/closure/spare-part/raw-data'
    | '/_authenticated/closure/task-management/dashboard'
    | '/_authenticated/closure/task-management/raw-data'
    | '/_authenticated/closure/task-management/schedule-revision'
    | '/_authenticated/closure/task-management/tree'
    | '/_authenticated/resource/dmr/dashboard'
    | '/_authenticated/resource/dmr/import'
    | '/_authenticated/resource/dmr/raw-data'
    | '/api/public/backup/archive-download'
    | '/api/public/backup/auto-snapshot'
    | '/_authenticated/closure/dashboard/'
    | '/_authenticated/closure/abd/import/logs'
    | '/_authenticated/closure/snag-management/detail/$id'
    | '/_authenticated/closure/snag-management/import/logs'
    | '/_authenticated/closure/spare-part/import/logs'
    | '/_authenticated/closure/spare-part/records/$docRef'
    | '/_authenticated/closure/task-management/detail/$id'
    | '/_authenticated/closure/task-management/import/logs'
    | '/_authenticated/closure/snag-management/import/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicBackupArchiveDownloadRoute: typeof ApiPublicBackupArchiveDownloadRoute
  ApiPublicBackupAutoSnapshotRoute: typeof ApiPublicBackupAutoSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resource/dashboard': {
      id: '/_authenticated/resource/dashboard'
      path: '/resource/dashboard'
      fullPath: '/resource/dashboard'
      preLoaderRoute: typeof AuthenticatedResourceDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outstanding/dashboard': {
      id: '/_authenticated/outstanding/dashboard'
      path: '/outstanding/dashboard'
      fullPath: '/outstanding/dashboard'
      preLoaderRoute: typeof AuthenticatedOutstandingDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-log/logs': {
      id: '/_authenticated/import-log/logs'
      path: '/import-log/logs'
      fullPath: '/import-log/logs'
      preLoaderRoute: typeof AuthenticatedImportLogLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-log/import': {
      id: '/_authenticated/import-log/import'
      path: '/import-log/import'
      fullPath: '/import-log/import'
      preLoaderRoute: typeof AuthenticatedImportLogImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closeout/dashboard': {
      id: '/_authenticated/closeout/dashboard'
      path: '/closeout/dashboard'
      fullPath: '/closeout/dashboard'
      preLoaderRoute: typeof AuthenticatedCloseoutDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/task-thresholds': {
      id: '/_authenticated/admin/task-thresholds'
      path: '/task-thresholds'
      fullPath: '/admin/task-thresholds'
      preLoaderRoute: typeof AuthenticatedAdminTaskThresholdsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/masters': {
      id: '/_authenticated/admin/masters'
      path: '/masters'
      fullPath: '/admin/masters'
      preLoaderRoute: typeof AuthenticatedAdminMastersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/mapping': {
      id: '/_authenticated/admin/mapping'
      path: '/mapping'
      fullPath: '/admin/mapping'
      preLoaderRoute: typeof AuthenticatedAdminMappingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/backup': {
      id: '/_authenticated/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AuthenticatedAdminBackupRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/closure/dashboard/': {
      id: '/_authenticated/closure/dashboard/'
      path: '/closure/dashboard'
      fullPath: '/closure/dashboard/'
      preLoaderRoute: typeof AuthenticatedClosureDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/backup/auto-snapshot': {
      id: '/api/public/backup/auto-snapshot'
      path: '/api/public/backup/auto-snapshot'
      fullPath: '/api/public/backup/auto-snapshot'
      preLoaderRoute: typeof ApiPublicBackupAutoSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup/archive-download': {
      id: '/api/public/backup/archive-download'
      path: '/api/public/backup/archive-download'
      fullPath: '/api/public/backup/archive-download'
      preLoaderRoute: typeof ApiPublicBackupArchiveDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resource/dmr/raw-data': {
      id: '/_authenticated/resource/dmr/raw-data'
      path: '/resource/dmr/raw-data'
      fullPath: '/resource/dmr/raw-data'
      preLoaderRoute: typeof AuthenticatedResourceDmrRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource/dmr/import': {
      id: '/_authenticated/resource/dmr/import'
      path: '/resource/dmr/import'
      fullPath: '/resource/dmr/import'
      preLoaderRoute: typeof AuthenticatedResourceDmrImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource/dmr/dashboard': {
      id: '/_authenticated/resource/dmr/dashboard'
      path: '/resource/dmr/dashboard'
      fullPath: '/resource/dmr/dashboard'
      preLoaderRoute: typeof AuthenticatedResourceDmrDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/tree': {
      id: '/_authenticated/closure/task-management/tree'
      path: '/closure/task-management/tree'
      fullPath: '/closure/task-management/tree'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementTreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/schedule-revision': {
      id: '/_authenticated/closure/task-management/schedule-revision'
      path: '/closure/task-management/schedule-revision'
      fullPath: '/closure/task-management/schedule-revision'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementScheduleRevisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/raw-data': {
      id: '/_authenticated/closure/task-management/raw-data'
      path: '/closure/task-management/raw-data'
      fullPath: '/closure/task-management/raw-data'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/dashboard': {
      id: '/_authenticated/closure/task-management/dashboard'
      path: '/closure/task-management/dashboard'
      fullPath: '/closure/task-management/dashboard'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/raw-data': {
      id: '/_authenticated/closure/spare-part/raw-data'
      path: '/closure/spare-part/raw-data'
      fullPath: '/closure/spare-part/raw-data'
      preLoaderRoute: typeof AuthenticatedClosureSparePartRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/import': {
      id: '/_authenticated/closure/spare-part/import'
      path: '/closure/spare-part/import'
      fullPath: '/closure/spare-part/import'
      preLoaderRoute: typeof AuthenticatedClosureSparePartImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/aconex-sync': {
      id: '/_authenticated/closure/spare-part/aconex-sync'
      path: '/closure/spare-part/aconex-sync'
      fullPath: '/closure/spare-part/aconex-sync'
      preLoaderRoute: typeof AuthenticatedClosureSparePartAconexSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/snag-management/settings': {
      id: '/_authenticated/closure/snag-management/settings'
      path: '/closure/snag-management/settings'
      fullPath: '/closure/snag-management/settings'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/snag-management/raw-data': {
      id: '/_authenticated/closure/snag-management/raw-data'
      path: '/closure/snag-management/raw-data'
      fullPath: '/closure/snag-management/raw-data'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/snag-management/progress': {
      id: '/_authenticated/closure/snag-management/progress'
      path: '/closure/snag-management/progress'
      fullPath: '/closure/snag-management/progress'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/snag-management/dashboard': {
      id: '/_authenticated/closure/snag-management/dashboard'
      path: '/closure/snag-management/dashboard'
      fullPath: '/closure/snag-management/dashboard'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/dashboard/warranty': {
      id: '/_authenticated/closure/dashboard/warranty'
      path: '/closure/dashboard/warranty'
      fullPath: '/closure/dashboard/warranty'
      preLoaderRoute: typeof AuthenticatedClosureDashboardWarrantyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/dashboard/task': {
      id: '/_authenticated/closure/dashboard/task'
      path: '/closure/dashboard/task'
      fullPath: '/closure/dashboard/task'
      preLoaderRoute: typeof AuthenticatedClosureDashboardTaskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/dashboard/spare-part': {
      id: '/_authenticated/closure/dashboard/spare-part'
      path: '/closure/dashboard/spare-part'
      fullPath: '/closure/dashboard/spare-part'
      preLoaderRoute: typeof AuthenticatedClosureDashboardSparePartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/dashboard/as-built': {
      id: '/_authenticated/closure/dashboard/as-built'
      path: '/closure/dashboard/as-built'
      fullPath: '/closure/dashboard/as-built'
      preLoaderRoute: typeof AuthenticatedClosureDashboardAsBuiltRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/abd/raw-data': {
      id: '/_authenticated/closure/abd/raw-data'
      path: '/closure/abd/raw-data'
      fullPath: '/closure/abd/raw-data'
      preLoaderRoute: typeof AuthenticatedClosureAbdRawDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/abd/progress': {
      id: '/_authenticated/closure/abd/progress'
      path: '/closure/abd/progress'
      fullPath: '/closure/abd/progress'
      preLoaderRoute: typeof AuthenticatedClosureAbdProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/abd/import': {
      id: '/_authenticated/closure/abd/import'
      path: '/closure/abd/import'
      fullPath: '/closure/abd/import'
      preLoaderRoute: typeof AuthenticatedClosureAbdImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/abd/dashboard': {
      id: '/_authenticated/closure/abd/dashboard'
      path: '/closure/abd/dashboard'
      fullPath: '/closure/abd/dashboard'
      preLoaderRoute: typeof AuthenticatedClosureAbdDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/snag-management/import/': {
      id: '/_authenticated/closure/snag-management/import/'
      path: '/closure/snag-management/import'
      fullPath: '/closure/snag-management/import/'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementImportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/import/logs': {
      id: '/_authenticated/closure/task-management/import/logs'
      path: '/closure/task-management/import/logs'
      fullPath: '/closure/task-management/import/logs'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementImportLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/task-management/detail/$id': {
      id: '/_authenticated/closure/task-management/detail/$id'
      path: '/closure/task-management/detail/$id'
      fullPath: '/closure/task-management/detail/$id'
      preLoaderRoute: typeof AuthenticatedClosureTaskManagementDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/records/$docRef': {
      id: '/_authenticated/closure/spare-part/records/$docRef'
      path: '/closure/spare-part/records/$docRef'
      fullPath: '/closure/spare-part/records/$docRef'
      preLoaderRoute: typeof AuthenticatedClosureSparePartRecordsDocRefRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/spare-part/import/logs': {
      id: '/_authenticated/closure/spare-part/import/logs'
      path: '/logs'
      fullPath: '/closure/spare-part/import/logs'
      preLoaderRoute: typeof AuthenticatedClosureSparePartImportLogsRouteImport
      parentRoute: typeof AuthenticatedClosureSparePartImportRoute
    }
    '/_authenticated/closure/snag-management/import/logs': {
      id: '/_authenticated/closure/snag-management/import/logs'
      path: '/closure/snag-management/import/logs'
      fullPath: '/closure/snag-management/import/logs'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementImportLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/snag-management/detail/$id': {
      id: '/_authenticated/closure/snag-management/detail/$id'
      path: '/closure/snag-management/detail/$id'
      fullPath: '/closure/snag-management/detail/$id'
      preLoaderRoute: typeof AuthenticatedClosureSnagManagementDetailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/closure/abd/import/logs': {
      id: '/_authenticated/closure/abd/import/logs'
      path: '/logs'
      fullPath: '/closure/abd/import/logs'
      preLoaderRoute: typeof AuthenticatedClosureAbdImportLogsRouteImport
      parentRoute: typeof AuthenticatedClosureAbdImportRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBackupRoute: typeof AuthenticatedAdminBackupRoute
  AuthenticatedAdminMappingRoute: typeof AuthenticatedAdminMappingRoute
  AuthenticatedAdminMastersRoute: typeof AuthenticatedAdminMastersRoute
  AuthenticatedAdminTaskThresholdsRoute: typeof AuthenticatedAdminTaskThresholdsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBackupRoute: AuthenticatedAdminBackupRoute,
    AuthenticatedAdminMappingRoute: AuthenticatedAdminMappingRoute,
    AuthenticatedAdminMastersRoute: AuthenticatedAdminMastersRoute,
    AuthenticatedAdminTaskThresholdsRoute:
      AuthenticatedAdminTaskThresholdsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClosureAbdImportRouteChildren {
  AuthenticatedClosureAbdImportLogsRoute: typeof AuthenticatedClosureAbdImportLogsRoute
}

const AuthenticatedClosureAbdImportRouteChildren: AuthenticatedClosureAbdImportRouteChildren =
  {
    AuthenticatedClosureAbdImportLogsRoute:
      AuthenticatedClosureAbdImportLogsRoute,
  }

const AuthenticatedClosureAbdImportRouteWithChildren =
  AuthenticatedClosureAbdImportRoute._addFileChildren(
    AuthenticatedClosureAbdImportRouteChildren,
  )

interface AuthenticatedClosureSparePartImportRouteChildren {
  AuthenticatedClosureSparePartImportLogsRoute: typeof AuthenticatedClosureSparePartImportLogsRoute
}

const AuthenticatedClosureSparePartImportRouteChildren: AuthenticatedClosureSparePartImportRouteChildren =
  {
    AuthenticatedClosureSparePartImportLogsRoute:
      AuthenticatedClosureSparePartImportLogsRoute,
  }

const AuthenticatedClosureSparePartImportRouteWithChildren =
  AuthenticatedClosureSparePartImportRoute._addFileChildren(
    AuthenticatedClosureSparePartImportRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCloseoutDashboardRoute: typeof AuthenticatedCloseoutDashboardRoute
  AuthenticatedImportLogImportRoute: typeof AuthenticatedImportLogImportRoute
  AuthenticatedImportLogLogsRoute: typeof AuthenticatedImportLogLogsRoute
  AuthenticatedOutstandingDashboardRoute: typeof AuthenticatedOutstandingDashboardRoute
  AuthenticatedResourceDashboardRoute: typeof AuthenticatedResourceDashboardRoute
  AuthenticatedClosureAbdDashboardRoute: typeof AuthenticatedClosureAbdDashboardRoute
  AuthenticatedClosureAbdImportRoute: typeof AuthenticatedClosureAbdImportRouteWithChildren
  AuthenticatedClosureAbdProgressRoute: typeof AuthenticatedClosureAbdProgressRoute
  AuthenticatedClosureAbdRawDataRoute: typeof AuthenticatedClosureAbdRawDataRoute
  AuthenticatedClosureDashboardAsBuiltRoute: typeof AuthenticatedClosureDashboardAsBuiltRoute
  AuthenticatedClosureDashboardSparePartRoute: typeof AuthenticatedClosureDashboardSparePartRoute
  AuthenticatedClosureDashboardTaskRoute: typeof AuthenticatedClosureDashboardTaskRoute
  AuthenticatedClosureDashboardWarrantyRoute: typeof AuthenticatedClosureDashboardWarrantyRoute
  AuthenticatedClosureSnagManagementDashboardRoute: typeof AuthenticatedClosureSnagManagementDashboardRoute
  AuthenticatedClosureSnagManagementProgressRoute: typeof AuthenticatedClosureSnagManagementProgressRoute
  AuthenticatedClosureSnagManagementRawDataRoute: typeof AuthenticatedClosureSnagManagementRawDataRoute
  AuthenticatedClosureSnagManagementSettingsRoute: typeof AuthenticatedClosureSnagManagementSettingsRoute
  AuthenticatedClosureSparePartAconexSyncRoute: typeof AuthenticatedClosureSparePartAconexSyncRoute
  AuthenticatedClosureSparePartImportRoute: typeof AuthenticatedClosureSparePartImportRouteWithChildren
  AuthenticatedClosureSparePartRawDataRoute: typeof AuthenticatedClosureSparePartRawDataRoute
  AuthenticatedClosureTaskManagementDashboardRoute: typeof AuthenticatedClosureTaskManagementDashboardRoute
  AuthenticatedClosureTaskManagementRawDataRoute: typeof AuthenticatedClosureTaskManagementRawDataRoute
  AuthenticatedClosureTaskManagementScheduleRevisionRoute: typeof AuthenticatedClosureTaskManagementScheduleRevisionRoute
  AuthenticatedClosureTaskManagementTreeRoute: typeof AuthenticatedClosureTaskManagementTreeRoute
  AuthenticatedResourceDmrDashboardRoute: typeof AuthenticatedResourceDmrDashboardRoute
  AuthenticatedResourceDmrImportRoute: typeof AuthenticatedResourceDmrImportRoute
  AuthenticatedResourceDmrRawDataRoute: typeof AuthenticatedResourceDmrRawDataRoute
  AuthenticatedClosureDashboardIndexRoute: typeof AuthenticatedClosureDashboardIndexRoute
  AuthenticatedClosureSnagManagementDetailIdRoute: typeof AuthenticatedClosureSnagManagementDetailIdRoute
  AuthenticatedClosureSnagManagementImportLogsRoute: typeof AuthenticatedClosureSnagManagementImportLogsRoute
  AuthenticatedClosureSparePartRecordsDocRefRoute: typeof AuthenticatedClosureSparePartRecordsDocRefRoute
  AuthenticatedClosureTaskManagementDetailIdRoute: typeof AuthenticatedClosureTaskManagementDetailIdRoute
  AuthenticatedClosureTaskManagementImportLogsRoute: typeof AuthenticatedClosureTaskManagementImportLogsRoute
  AuthenticatedClosureSnagManagementImportIndexRoute: typeof AuthenticatedClosureSnagManagementImportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCloseoutDashboardRoute: AuthenticatedCloseoutDashboardRoute,
  AuthenticatedImportLogImportRoute: AuthenticatedImportLogImportRoute,
  AuthenticatedImportLogLogsRoute: AuthenticatedImportLogLogsRoute,
  AuthenticatedOutstandingDashboardRoute:
    AuthenticatedOutstandingDashboardRoute,
  AuthenticatedResourceDashboardRoute: AuthenticatedResourceDashboardRoute,
  AuthenticatedClosureAbdDashboardRoute: AuthenticatedClosureAbdDashboardRoute,
  AuthenticatedClosureAbdImportRoute:
    AuthenticatedClosureAbdImportRouteWithChildren,
  AuthenticatedClosureAbdProgressRoute: AuthenticatedClosureAbdProgressRoute,
  AuthenticatedClosureAbdRawDataRoute: AuthenticatedClosureAbdRawDataRoute,
  AuthenticatedClosureDashboardAsBuiltRoute:
    AuthenticatedClosureDashboardAsBuiltRoute,
  AuthenticatedClosureDashboardSparePartRoute:
    AuthenticatedClosureDashboardSparePartRoute,
  AuthenticatedClosureDashboardTaskRoute:
    AuthenticatedClosureDashboardTaskRoute,
  AuthenticatedClosureDashboardWarrantyRoute:
    AuthenticatedClosureDashboardWarrantyRoute,
  AuthenticatedClosureSnagManagementDashboardRoute:
    AuthenticatedClosureSnagManagementDashboardRoute,
  AuthenticatedClosureSnagManagementProgressRoute:
    AuthenticatedClosureSnagManagementProgressRoute,
  AuthenticatedClosureSnagManagementRawDataRoute:
    AuthenticatedClosureSnagManagementRawDataRoute,
  AuthenticatedClosureSnagManagementSettingsRoute:
    AuthenticatedClosureSnagManagementSettingsRoute,
  AuthenticatedClosureSparePartAconexSyncRoute:
    AuthenticatedClosureSparePartAconexSyncRoute,
  AuthenticatedClosureSparePartImportRoute:
    AuthenticatedClosureSparePartImportRouteWithChildren,
  AuthenticatedClosureSparePartRawDataRoute:
    AuthenticatedClosureSparePartRawDataRoute,
  AuthenticatedClosureTaskManagementDashboardRoute:
    AuthenticatedClosureTaskManagementDashboardRoute,
  AuthenticatedClosureTaskManagementRawDataRoute:
    AuthenticatedClosureTaskManagementRawDataRoute,
  AuthenticatedClosureTaskManagementScheduleRevisionRoute:
    AuthenticatedClosureTaskManagementScheduleRevisionRoute,
  AuthenticatedClosureTaskManagementTreeRoute:
    AuthenticatedClosureTaskManagementTreeRoute,
  AuthenticatedResourceDmrDashboardRoute:
    AuthenticatedResourceDmrDashboardRoute,
  AuthenticatedResourceDmrImportRoute: AuthenticatedResourceDmrImportRoute,
  AuthenticatedResourceDmrRawDataRoute: AuthenticatedResourceDmrRawDataRoute,
  AuthenticatedClosureDashboardIndexRoute:
    AuthenticatedClosureDashboardIndexRoute,
  AuthenticatedClosureSnagManagementDetailIdRoute:
    AuthenticatedClosureSnagManagementDetailIdRoute,
  AuthenticatedClosureSnagManagementImportLogsRoute:
    AuthenticatedClosureSnagManagementImportLogsRoute,
  AuthenticatedClosureSparePartRecordsDocRefRoute:
    AuthenticatedClosureSparePartRecordsDocRefRoute,
  AuthenticatedClosureTaskManagementDetailIdRoute:
    AuthenticatedClosureTaskManagementDetailIdRoute,
  AuthenticatedClosureTaskManagementImportLogsRoute:
    AuthenticatedClosureTaskManagementImportLogsRoute,
  AuthenticatedClosureSnagManagementImportIndexRoute:
    AuthenticatedClosureSnagManagementImportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicBackupArchiveDownloadRoute: ApiPublicBackupArchiveDownloadRoute,
  ApiPublicBackupAutoSnapshotRoute: ApiPublicBackupAutoSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
